# Generated by Django 4.2.5 on 2023-10-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
